## ReadOS
# By BinBash
# .zshrc default file
###################################################################################
# DO NOT EDIT THIS FILE... WRITE YOUR PERSONAL ZSH CONFIG IN ~/.zshrc-personal file
# DO NOT EDIT THIS FILE... WRITE YOUR PERSONAL ZSH CONFIG IN ~/.zshrc-personal file
# DO NOT EDIT THIS FILE... WRITE YOUR PERSONAL ZSH CONFIG IN ~/.zshrc-personal file
###################################################################################

export TERM=termite
[[ ! -f /usr/share/fzf/completion-ia.zsh ]] || source /usr/share/fzf/completion-ia.zsh
[[ ! -f /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh ]] || source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

case $TERM in
  xterm*)
    precmd () {print -Pn "\e]0;%~\a"}
    ;;
esac

# History Configuration
HISTSIZE=5000               #How many lines of history to keep in memory
HISTFILE=~/.zsh_history     #Where to save history to disk
SAVEHIST=5000               #Number of history entries to save to disk
#HISTDUP=erase               #Erase duplicates in the history file
setopt    appendhistory     #Append history to the history file (no overwriting)
setopt    sharehistory      #Share history across terminals
setopt    incappendhistory  #Immediately append to the history file, not just when a term is killed

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

[[ ! -f /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme ]] || source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Personal config file 
[[ ! -f ~/.zshrc-personal ]] || source ~/.zshrc-personal
# fnm
export PATH=/home/jhonathan/.local/bin:$PATH
eval "`fnm env`"
